<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__AlBVNIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..alBVNI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..alBVNI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'districtRepository' => ['privates', 'App\\Repository\\DistrictRepository', 'getDistrictRepositoryService', true],
        ], [
            'districtRepository' => 'App\\Repository\\DistrictRepository',
        ]);
    }
}
