<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DybQibGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DybQibG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DybQibG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alerteRepository' => ['privates', 'App\\Repository\\AlerteRepository', 'getAlerteRepositoryService', true],
        ], [
            'alerteRepository' => 'App\\Repository\\AlerteRepository',
        ]);
    }
}
