<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LdM_XmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LdM_.Xm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LdM_.Xm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paiementService' => ['privates', 'App\\Service\\PaiementService', 'getPaiementServiceService', true],
        ], [
            'paiementService' => 'App\\Service\\PaiementService',
        ]);
    }
}
