<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PTW4rAJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pTW4rAJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pTW4rAJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professionnel' => ['privates', '.errored..service_locator.pTW4rAJ.App\\Entity\\Professionnel', NULL, 'Cannot autowire service ".service_locator.pTW4rAJ": it needs an instance of "App\\Entity\\Professionnel" but this type has been excluded in "config/services.yaml".'],
            'professionnelRepository' => ['privates', 'App\\Repository\\ProfessionnelRepository', 'getProfessionnelRepositoryService', true],
        ], [
            'professionnel' => 'App\\Entity\\Professionnel',
            'professionnelRepository' => 'App\\Repository\\ProfessionnelRepository',
        ]);
    }
}
