<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiVilleControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PwpX3fN.App\Controller\Apis\ApiVilleController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PwpX3fN.App\\Controller\\Apis\\ApiVilleController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ville' => ['privates', '.errored..service_locator.PwpX3fN.App\\Entity\\Ville', NULL, 'Cannot autowire service ".service_locator.PwpX3fN": it needs an instance of "App\\Entity\\Ville" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
        ], [
            'ville' => 'App\\Entity\\Ville',
            'villeRepository' => 'App\\Repository\\VilleRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiVilleController::delete()', $container);
    }
}
