<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaiementControllerindexInfoTransactionLastTransactionFormatterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4vi5b.A.App\Controller\Apis\ApiPaiementController::indexInfoTransactionLastTransactionFormatter()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4vi5b.A.App\\Controller\\Apis\\ApiPaiementController::indexInfoTransactionLastTransactionFormatter()'] = ($container->privates['.service_locator.4vi5b.A'] ?? $container->load('get_ServiceLocator_4vi5b_AService'))->withContext('App\\Controller\\Apis\\ApiPaiementController::indexInfoTransactionLastTransactionFormatter()', $container);
    }
}
