<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaiementControllerstatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tkd802a.App\Controller\Apis\ApiPaiementController::status()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tkd802a.App\\Controller\\Apis\\ApiPaiementController::status()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'professionRepository' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
        ], [
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'professionRepository' => 'App\\Repository\\ProfessionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiPaiementController::status()', $container);
    }
}
