<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAlerteControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LS4zByK.App\Controller\Apis\ApiAlerteController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LS4zByK.App\\Controller\\Apis\\ApiAlerteController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alerte' => ['privates', '.errored..service_locator.LS4zByK.App\\Entity\\Alerte', NULL, 'Cannot autowire service ".service_locator.LS4zByK": it needs an instance of "App\\Entity\\Alerte" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\AlerteRepository', 'getAlerteRepositoryService', true],
        ], [
            'alerte' => 'App\\Entity\\Alerte',
            'villeRepository' => 'App\\Repository\\AlerteRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiAlerteController::delete()', $container);
    }
}
