<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDocument2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ab2O3uR.App\Entity\AdminDocument' shared service.
     *
     * @return \App\Entity\AdminDocument
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ab2O3uR": it needs an instance of "App\\Entity\\AdminDocument" but this type has been excluded in "config/services.yaml".');
    }
}
