<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiSpecialiteControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eT3_6ZI.App\Controller\Apis\ApiSpecialiteController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eT3_6ZI.App\\Controller\\Apis\\ApiSpecialiteController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'specialite' => ['privates', '.errored..service_locator.eT3_6ZI.App\\Entity\\Specialite', NULL, 'Cannot autowire service ".service_locator.eT3_6ZI": it needs an instance of "App\\Entity\\Specialite" but this type has been excluded in "config/services.yaml".'],
            'specialiteRepository' => ['privates', 'App\\Repository\\SpecialiteRepository', 'getSpecialiteRepositoryService', true],
        ], [
            'specialite' => 'App\\Entity\\Specialite',
            'specialiteRepository' => 'App\\Repository\\SpecialiteRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiSpecialiteController::update()', $container);
    }
}
