<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeDocumentControllergetDocByTypePersonneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4UpMJNr.App\Controller\Apis\ApiTypeDocumentController::getDocByTypePersonne()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4UpMJNr.App\\Controller\\Apis\\ApiTypeDocumentController::getDocByTypePersonne()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeDocumentRepository' => ['privates', 'App\\Repository\\TypeDocumentRepository', 'getTypeDocumentRepositoryService', true],
        ], [
            'typeDocumentRepository' => 'App\\Repository\\TypeDocumentRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiTypeDocumentController::getDocByTypePersonne()', $container);
    }
}
