<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MEpC8W1.App\Controller\Apis\ApiProfessionController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MEpC8W1.App\\Controller\\Apis\\ApiProfessionController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professionRepository' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
            'typeProfessionRepository' => ['privates', 'App\\Repository\\TypeProfessionRepository', 'getTypeProfessionRepositoryService', true],
        ], [
            'professionRepository' => 'App\\Repository\\ProfessionRepository',
            'typeProfessionRepository' => 'App\\Repository\\TypeProfessionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiProfessionController::create()', $container);
    }
}
