<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeProfessionControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2lDAJvg.App\Controller\Apis\ApiTypeProfessionController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2lDAJvg.App\\Controller\\Apis\\ApiTypeProfessionController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeProfession' => ['privates', '.errored..service_locator.2lDAJvg.App\\Entity\\TypeProfession', NULL, 'Cannot autowire service ".service_locator.2lDAJvg": it needs an instance of "App\\Entity\\TypeProfession" but this type has been excluded in "config/services.yaml".'],
            'typeProfessionRepository' => ['privates', 'App\\Repository\\TypeProfessionRepository', 'getTypeProfessionRepositoryService', true],
        ], [
            'typeProfession' => 'App\\Entity\\TypeProfession',
            'typeProfessionRepository' => 'App\\Repository\\TypeProfessionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiTypeProfessionController::update()', $container);
    }
}
