<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeDiplomeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FyksVHQ.App\Controller\Apis\ApiTypeDiplomeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FyksVHQ.App\\Controller\\Apis\\ApiTypeDiplomeController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeDiplome' => ['privates', '.errored..service_locator.FyksVHQ.App\\Entity\\TypeDiplome', NULL, 'Cannot autowire service ".service_locator.FyksVHQ": it needs an instance of "App\\Entity\\TypeDiplome" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\TypeDiplomeRepository', 'getTypeDiplomeRepositoryService', true],
        ], [
            'typeDiplome' => 'App\\Entity\\TypeDiplome',
            'villeRepository' => 'App\\Repository\\TypeDiplomeRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiTypeDiplomeController::delete()', $container);
    }
}
