<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiNotificationControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8dODJ0F.App\Controller\Apis\ApiNotificationController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8dODJ0F.App\\Controller\\Apis\\ApiNotificationController::update()'] = ($container->privates['.service_locator.8dODJ0F'] ?? $container->load('get_ServiceLocator_8dODJ0FService'))->withContext('App\\Controller\\Apis\\ApiNotificationController::update()', $container);
    }
}
