<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionControllergetMontantsOptionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PdKK4sX.App\Controller\Apis\ApiProfessionController::getMontantsOptions()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PdKK4sX.App\\Controller\\Apis\\ApiProfessionController::getMontantsOptions()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ProfessionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiProfessionController::getMontantsOptions()', $container);
    }
}
