<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAdminDocumentControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.udLrYBI.App\Controller\Apis\ApiAdminDocumentController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.udLrYBI.App\\Controller\\Apis\\ApiAdminDocumentController::index()'] = ($container->privates['.service_locator.udLrYBI'] ?? $container->load('get_ServiceLocator_UdLrYBIService'))->withContext('App\\Controller\\Apis\\ApiAdminDocumentController::index()', $container);
    }
}
