<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUserControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D0iGBCI.App\Controller\Apis\ApiUserController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D0iGBCI.App\\Controller\\Apis\\ApiUserController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.D0iGBCI.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.D0iGBCI": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'administrateurRepository' => ['privates', 'App\\Repository\\AdministrateurRepository', 'getAdministrateurRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'userRepository' => 'App\\Repository\\UserRepository',
            'administrateurRepository' => 'App\\Repository\\AdministrateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiUserController::update()', $container);
    }
}
