<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiStatusProControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K8kGn5w.App\Controller\Apis\ApiStatusProController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K8kGn5w.App\\Controller\\Apis\\ApiStatusProController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\StatusProRepository', 'getStatusProRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\StatusProRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiStatusProController::deleteAll()', $container);
    }
}
