<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCiviliteControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BI8T.0K.App\Controller\Apis\ApiCiviliteController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BI8T.0K.App\\Controller\\Apis\\ApiCiviliteController::create()'] = ($container->privates['.service_locator.BI8T.0K'] ?? $container->load('get_ServiceLocator_BI8T_0KService'))->withContext('App\\Controller\\Apis\\ApiCiviliteController::create()', $container);
    }
}
