<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaysControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A_7_GOg.App\Controller\Apis\ApiPaysController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A_7_GOg.App\\Controller\\Apis\\ApiPaysController::index()'] = ($container->privates['.service_locator.A_7_GOg'] ?? $container->load('get_ServiceLocator_A7GOgService'))->withContext('App\\Controller\\Apis\\ApiPaysController::index()', $container);
    }
}
