<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAvisControlleravisForumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9SI.kqC.App\Controller\Apis\ApiAvisController::avisForum()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9SI.kqC.App\\Controller\\Apis\\ApiAvisController::avisForum()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'forum' => ['privates', '.errored..service_locator.9SI.kqC.App\\Entity\\Forum', NULL, 'Cannot autowire service ".service_locator.9SI.kqC": it needs an instance of "App\\Entity\\Forum" but this type has been excluded in "config/services.yaml".'],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'forum' => 'App\\Entity\\Forum',
        ]))->withContext('App\\Controller\\Apis\\ApiAvisController::avisForum()', $container);
    }
}
