<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiStatusProControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hrYaLBT.App\Controller\Apis\ApiStatusProController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hrYaLBT.App\\Controller\\Apis\\ApiStatusProController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statusPro' => ['privates', '.errored..service_locator.hrYaLBT.App\\Entity\\StatusPro', NULL, 'Cannot autowire service ".service_locator.hrYaLBT": it needs an instance of "App\\Entity\\StatusPro" but this type has been excluded in "config/services.yaml".'],
            'statusProRepository' => ['privates', 'App\\Repository\\StatusProRepository', 'getStatusProRepositoryService', true],
        ], [
            'statusPro' => 'App\\Entity\\StatusPro',
            'statusProRepository' => 'App\\Repository\\StatusProRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiStatusProController::update()', $container);
    }
}
