<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAvisControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RdCNn2J.App\Controller\Apis\ApiAvisController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RdCNn2J.App\\Controller\\Apis\\ApiAvisController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'forumRepository' => ['privates', 'App\\Repository\\ForumRepository', 'getForumRepositoryService', true],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'forumRepository' => 'App\\Repository\\ForumRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiAvisController::create()', $container);
    }
}
