<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiSituationProfessionnelleControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r59Tk6E.App\Controller\Apis\ApiSituationProfessionnelleController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r59Tk6E.App\\Controller\\Apis\\ApiSituationProfessionnelleController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'situationProfessionnelle' => ['privates', '.errored..service_locator.r59Tk6E.App\\Entity\\SituationProfessionnelle', NULL, 'Cannot autowire service ".service_locator.r59Tk6E": it needs an instance of "App\\Entity\\SituationProfessionnelle" but this type has been excluded in "config/services.yaml".'],
            'situationProfessionnelleRepository' => ['privates', 'App\\Repository\\SituationProfessionnelleRepository', 'getSituationProfessionnelleRepositoryService', true],
        ], [
            'situationProfessionnelle' => 'App\\Entity\\SituationProfessionnelle',
            'situationProfessionnelleRepository' => 'App\\Repository\\SituationProfessionnelleRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiSituationProfessionnelleController::update()', $container);
    }
}
