<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCodeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qufvey0.App\Controller\Apis\ApiCodeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qufvey0.App\\Controller\\Apis\\ApiCodeController::index()'] = ($container->privates['.service_locator.Qufvey0'] ?? $container->load('get_ServiceLocator_Qufvey0Service'))->withContext('App\\Controller\\Apis\\ApiCodeController::index()', $container);
    }
}
