<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiEtablissementControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K_dLY6..App\Controller\Apis\ApiEtablissementController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K_dLY6..App\\Controller\\Apis\\ApiEtablissementController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utils' => ['privates', 'App\\Service\\Utils', 'getUtilsService', true],
            'libelleGroupeRepository' => ['privates', 'App\\Repository\\LibelleGroupeRepository', 'getLibelleGroupeRepositoryService', true],
            'typePersonneRepository' => ['privates', 'App\\Repository\\TypePersonneRepository', 'getTypePersonneRepositoryService', true],
            'etablissementRepository' => ['privates', 'App\\Repository\\EtablissementRepository', 'getEtablissementRepositoryService', true],
            'documentRepository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
            'niveauInterventionRepository' => ['privates', 'App\\Repository\\NiveauInterventionRepository', 'getNiveauInterventionRepositoryService', true],
        ], [
            'utils' => 'App\\Service\\Utils',
            'libelleGroupeRepository' => 'App\\Repository\\LibelleGroupeRepository',
            'typePersonneRepository' => 'App\\Repository\\TypePersonneRepository',
            'etablissementRepository' => 'App\\Repository\\EtablissementRepository',
            'documentRepository' => 'App\\Repository\\DocumentRepository',
            'niveauInterventionRepository' => 'App\\Repository\\NiveauInterventionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiEtablissementController::update()', $container);
    }
}
