<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiEtablissementControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BOvB7lT.App\Controller\Apis\ApiEtablissementController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BOvB7lT.App\\Controller\\Apis\\ApiEtablissementController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etablissement' => ['privates', '.errored..service_locator.BOvB7lT.App\\Entity\\Etablissement', NULL, 'Cannot autowire service ".service_locator.BOvB7lT": it needs an instance of "App\\Entity\\Etablissement" but this type has been excluded in "config/services.yaml".'],
            'etablissementRepository' => ['privates', 'App\\Repository\\EtablissementRepository', 'getEtablissementRepositoryService', true],
        ], [
            'etablissement' => 'App\\Entity\\Etablissement',
            'etablissementRepository' => 'App\\Repository\\EtablissementRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiEtablissementController::delete()', $container);
    }
}
