<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiNotificationControllerindexNombreNotificationNonluService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XktpCeC.App\Controller\Apis\ApiNotificationController::indexNombreNotificationNonlu()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XktpCeC.App\\Controller\\Apis\\ApiNotificationController::indexNombreNotificationNonlu()'] = ($container->privates['.service_locator.XktpCeC'] ?? $container->load('get_ServiceLocator_XktpCeCService'))->withContext('App\\Controller\\Apis\\ApiNotificationController::indexNombreNotificationNonlu()', $container);
    }
}
