<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeDiplomeControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2XmFxZU.App\Controller\Apis\ApiTypeDiplomeController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2XmFxZU.App\\Controller\\Apis\\ApiTypeDiplomeController::create()'] = ($container->privates['.service_locator.2XmFxZU'] ?? $container->load('get_ServiceLocator_2XmFxZUService'))->withContext('App\\Controller\\Apis\\ApiTypeDiplomeController::create()', $container);
    }
}
