<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRegionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bmKHffE.App\Controller\Apis\ApiRegionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bmKHffE.App\\Controller\\Apis\\ApiRegionController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'region' => ['privates', '.errored..service_locator.bmKHffE.App\\Entity\\Region', NULL, 'Cannot autowire service ".service_locator.bmKHffE": it needs an instance of "App\\Entity\\Region" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService', true],
        ], [
            'region' => 'App\\Entity\\Region',
            'villeRepository' => 'App\\Repository\\RegionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiRegionController::delete()', $container);
    }
}
