<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypePersonneControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qdUEtu2.App\Controller\Apis\ApiTypePersonneController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qdUEtu2.App\\Controller\\Apis\\ApiTypePersonneController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typePersonne' => ['privates', '.errored..service_locator.qdUEtu2.App\\Entity\\TypePersonne', NULL, 'Cannot autowire service ".service_locator.qdUEtu2": it needs an instance of "App\\Entity\\TypePersonne" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\TypePersonneRepository', 'getTypePersonneRepositoryService', true],
        ], [
            'typePersonne' => 'App\\Entity\\TypePersonne',
            'villeRepository' => 'App\\Repository\\TypePersonneRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiTypePersonneController::delete()', $container);
    }
}
