<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDestinateurControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1NGhZlv.App\Controller\Apis\ApiDestinateurController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1NGhZlv.App\\Controller\\Apis\\ApiDestinateurController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\DestinateurRepository', 'getDestinateurRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\DestinateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiDestinateurController::deleteAll()', $container);
    }
}
