<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLibelleGroupeControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aRok4c2.App\Controller\Apis\ApiLibelleGroupeController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aRok4c2.App\\Controller\\Apis\\ApiLibelleGroupeController::create()'] = ($container->privates['.service_locator.aRok4c2'] ?? $container->load('get_ServiceLocator_ARok4c2Service'))->withContext('App\\Controller\\Apis\\ApiLibelleGroupeController::create()', $container);
    }
}
