<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLibelleGroupeControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XCS6QHK.App\Controller\Apis\ApiLibelleGroupeController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XCS6QHK.App\\Controller\\Apis\\ApiLibelleGroupeController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\LibelleGroupeRepository', 'getLibelleGroupeRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\LibelleGroupeRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiLibelleGroupeController::deleteAll()', $container);
    }
}
