<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRacineSequenceControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.be8gbrq.App\Controller\Apis\ApiRacineSequenceController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.be8gbrq.App\\Controller\\Apis\\ApiRacineSequenceController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'racineSequence' => ['privates', '.errored..service_locator.be8gbrq.App\\Entity\\RacineSequence', NULL, 'Cannot autowire service ".service_locator.be8gbrq": it needs an instance of "App\\Entity\\RacineSequence" but this type has been excluded in "config/services.yaml".'],
            'racineSequenceRepository' => ['privates', 'App\\Repository\\RacineSequenceRepository', 'getRacineSequenceRepositoryService', true],
        ], [
            'racineSequence' => 'App\\Entity\\RacineSequence',
            'racineSequenceRepository' => 'App\\Repository\\RacineSequenceRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiRacineSequenceController::update()', $container);
    }
}
