<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUserControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OZAhiMp.App\Controller\Apis\ApiUserController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OZAhiMp.App\\Controller\\Apis\\ApiUserController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'sendMailService' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'sendMailService' => 'App\\Service\\SendMailService',
        ]))->withContext('App\\Controller\\Apis\\ApiUserController::create()', $container);
    }
}
