<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaiementControllerinitieOpeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SwHFkcU.App\Controller\Apis\ApiPaiementController::initieOpe()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SwHFkcU.App\\Controller\\Apis\\ApiPaiementController::initieOpe()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paiementService' => ['privates', 'App\\Service\\PaiementService', 'getPaiementServiceService', true],
            'etablissementRepository' => ['privates', 'App\\Repository\\EtablissementRepository', 'getEtablissementRepositoryService', true],
            'documentOepTempRepository' => ['privates', 'App\\Repository\\DocumentOepTempRepository', 'getDocumentOepTempRepositoryService', true],
        ], [
            'paiementService' => 'App\\Service\\PaiementService',
            'etablissementRepository' => 'App\\Repository\\EtablissementRepository',
            'documentOepTempRepository' => 'App\\Repository\\DocumentOepTempRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiPaiementController::initieOpe()', $container);
    }
}
