<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiArticleControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WNKzgiP.App\Controller\Apis\ApiArticleController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WNKzgiP.App\\Controller\\Apis\\ApiArticleController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.WNKzgiP.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.WNKzgiP": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'articleRepository' => 'App\\Repository\\ArticleRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiArticleController::update()', $container);
    }
}
