<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiForumControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0sWRPCt.App\Controller\Apis\ApiForumController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0sWRPCt.App\\Controller\\Apis\\ApiForumController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'forum' => ['privates', '.errored..service_locator.0sWRPCt.App\\Entity\\Forum', NULL, 'Cannot autowire service ".service_locator.0sWRPCt": it needs an instance of "App\\Entity\\Forum" but this type has been excluded in "config/services.yaml".'],
            'forumRepository' => ['privates', 'App\\Repository\\ForumRepository', 'getForumRepositoryService', true],
        ], [
            'forum' => 'App\\Entity\\Forum',
            'forumRepository' => 'App\\Repository\\ForumRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiForumController::update()', $container);
    }
}
