<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCommuneControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dzZpI_n.App\Controller\Apis\ApiCommuneController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dzZpI_n.App\\Controller\\Apis\\ApiCommuneController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commune' => ['privates', '.errored..service_locator.dzZpI_n.App\\Entity\\Commune', NULL, 'Cannot autowire service ".service_locator.dzZpI_n": it needs an instance of "App\\Entity\\Commune" but this type has been excluded in "config/services.yaml".'],
            'communeRepository' => ['privates', 'App\\Repository\\CommuneRepository', 'getCommuneRepositoryService', true],
            'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
        ], [
            'commune' => 'App\\Entity\\Commune',
            'communeRepository' => 'App\\Repository\\CommuneRepository',
            'villeRepository' => 'App\\Repository\\VilleRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCommuneController::update()', $container);
    }
}
