<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLieuDiplomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XzwBRpl.App\Controller\Apis\ApiLieuDiplomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XzwBRpl.App\\Controller\\Apis\\ApiLieuDiplomeController::index()'] = ($container->privates['.service_locator.XzwBRpl'] ?? $container->load('get_ServiceLocator_XzwBRplService'))->withContext('App\\Controller\\Apis\\ApiLieuDiplomeController::index()', $container);
    }
}
