<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCodeGenerateurControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0EXbsy8.App\Controller\Apis\ApiCodeGenerateurController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0EXbsy8.App\\Controller\\Apis\\ApiCodeGenerateurController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'codeGenerateurRepository' => ['privates', 'App\\Repository\\CodeGenerateurRepository', 'getCodeGenerateurRepositoryService', true],
        ], [
            'codeGenerateurRepository' => 'App\\Repository\\CodeGenerateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCodeGenerateurController::index()', $container);
    }
}
