<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDistrictControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TdfX6T..App\Controller\Apis\ApiDistrictController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TdfX6T..App\\Controller\\Apis\\ApiDistrictController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\DistrictRepository', 'getDistrictRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\DistrictRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiDistrictController::deleteAll()', $container);
    }
}
