<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCodeGenerateurControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QQB.3t3.App\Controller\Apis\ApiCodeGenerateurController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QQB.3t3.App\\Controller\\Apis\\ApiCodeGenerateurController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'codeGenerateur' => ['privates', '.errored..service_locator.QQB.3t3.App\\Entity\\CodeGenerateur', NULL, 'Cannot autowire service ".service_locator.QQB.3t3": it needs an instance of "App\\Entity\\CodeGenerateur" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\CodeGenerateurRepository', 'getCodeGenerateurRepositoryService', true],
        ], [
            'codeGenerateur' => 'App\\Entity\\CodeGenerateur',
            'villeRepository' => 'App\\Repository\\CodeGenerateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCodeGenerateurController::delete()', $container);
    }
}
