<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCodeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aYwRAn9.App\Controller\Apis\ApiCodeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aYwRAn9.App\\Controller\\Apis\\ApiCodeController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'code' => ['privates', '.errored..service_locator.aYwRAn9.App\\Entity\\Code', NULL, 'Cannot autowire service ".service_locator.aYwRAn9": it needs an instance of "App\\Entity\\Code" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\CodeRepository', 'getCodeRepositoryService', true],
        ], [
            'code' => 'App\\Entity\\Code',
            'villeRepository' => 'App\\Repository\\CodeRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCodeController::delete()', $container);
    }
}
