<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiSituationProfessionnelleControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.alYptO1.App\Controller\Apis\ApiSituationProfessionnelleController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.alYptO1.App\\Controller\\Apis\\ApiSituationProfessionnelleController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\SituationProfessionnelleRepository', 'getSituationProfessionnelleRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\SituationProfessionnelleRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiSituationProfessionnelleController::deleteAll()', $container);
    }
}
