<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCiviliteControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0hl7XJu.App\Controller\Apis\ApiCiviliteController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0hl7XJu.App\\Controller\\Apis\\ApiCiviliteController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'civilite' => ['privates', '.errored..service_locator.0hl7XJu.App\\Entity\\Civilite', NULL, 'Cannot autowire service ".service_locator.0hl7XJu": it needs an instance of "App\\Entity\\Civilite" but this type has been excluded in "config/services.yaml".'],
            'civiliteRepository' => ['privates', 'App\\Repository\\CiviliteRepository', 'getCiviliteRepositoryService', true],
        ], [
            'civilite' => 'App\\Entity\\Civilite',
            'civiliteRepository' => 'App\\Repository\\CiviliteRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCiviliteController::update()', $container);
    }
}
