<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRegionControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wVAstm0.App\Controller\Apis\ApiRegionController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wVAstm0.App\\Controller\\Apis\\ApiRegionController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'regionRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService', true],
        ], [
            'regionRepository' => 'App\\Repository\\RegionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiRegionController::index()', $container);
    }
}
