<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiNotificationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u99T1QH.App\Controller\Apis\ApiNotificationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u99T1QH.App\\Controller\\Apis\\ApiNotificationController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notification' => ['privates', '.errored..service_locator.u99T1QH.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.u99T1QH": it needs an instance of "App\\Entity\\Notification" but this type has been excluded in "config/services.yaml".'],
            'notificationRepository' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
        ], [
            'notification' => 'App\\Entity\\Notification',
            'notificationRepository' => 'App\\Repository\\NotificationRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiNotificationController::delete()', $container);
    }
}
