<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiEtablissementControlleractiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j.jIvEQ.App\Controller\Apis\ApiEtablissementController::active()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j.jIvEQ.App\\Controller\\Apis\\ApiEtablissementController::active()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etablissement' => ['privates', '.errored..service_locator.j.jIvEQ.App\\Entity\\Etablissement', NULL, 'Cannot autowire service ".service_locator.j.jIvEQ": it needs an instance of "App\\Entity\\Etablissement" but this type has been excluded in "config/services.yaml".'],
            'etablissementRepository' => ['privates', 'App\\Repository\\EtablissementRepository', 'getEtablissementRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
            'workflowRegistry' => ['privates', 'workflow.registry', 'getWorkflow_RegistryService', false],
            'sendMailService' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
            'utils' => ['privates', 'App\\Service\\Utils', 'getUtilsService', true],
        ], [
            'etablissement' => 'App\\Entity\\Etablissement',
            'etablissementRepository' => 'App\\Repository\\EtablissementRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'validator' => '?',
            'workflowRegistry' => '?',
            'sendMailService' => 'App\\Service\\SendMailService',
            'utils' => 'App\\Service\\Utils',
        ]))->withContext('App\\Controller\\Apis\\ApiEtablissementController::active()', $container);
    }
}
