<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiValidationWorkflowControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sBl1DdK.App\Controller\Apis\ApiValidationWorkflowController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sBl1DdK.App\\Controller\\Apis\\ApiValidationWorkflowController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ValidationWorkflow' => ['privates', '.errored..service_locator.sBl1DdK.App\\Entity\\ValidationWorkflow', NULL, 'Cannot autowire service ".service_locator.sBl1DdK": it needs an instance of "App\\Entity\\ValidationWorkflow" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\ValidationWorkflowRepository', 'getValidationWorkflowRepositoryService', true],
        ], [
            'ValidationWorkflow' => 'App\\Entity\\ValidationWorkflow',
            'villeRepository' => 'App\\Repository\\ValidationWorkflowRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiValidationWorkflowController::delete()', $container);
    }
}
