<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLibelleGroupeControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ETUrCGm.App\Controller\Apis\ApiLibelleGroupeController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ETUrCGm.App\\Controller\\Apis\\ApiLibelleGroupeController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'libelleGroupe' => ['privates', '.errored..service_locator.ETUrCGm.App\\Entity\\LibelleGroupe', NULL, 'Cannot autowire service ".service_locator.ETUrCGm": it needs an instance of "App\\Entity\\LibelleGroupe" but this type has been excluded in "config/services.yaml".'],
            'libelleGroupeRepository' => ['privates', 'App\\Repository\\LibelleGroupeRepository', 'getLibelleGroupeRepositoryService', true],
        ], [
            'libelleGroupe' => 'App\\Entity\\LibelleGroupe',
            'libelleGroupeRepository' => 'App\\Repository\\LibelleGroupeRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiLibelleGroupeController::update()', $container);
    }
}
