<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionControllergetPaiementStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W.Q_E8n.App\Controller\Apis\ApiProfessionController::getPaiementStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W.Q_E8n.App\\Controller\\Apis\\ApiProfessionController::getPaiementStatus()'] = ($container->privates['.service_locator.W.Q_E8n'] ?? $container->load('get_ServiceLocator_W_QE8nService'))->withContext('App\\Controller\\Apis\\ApiProfessionController::getPaiementStatus()', $container);
    }
}
