<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAdminDocumentControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ab2O3uR.App\Controller\Apis\ApiAdminDocumentController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ab2O3uR.App\\Controller\\Apis\\ApiAdminDocumentController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adminDocument' => ['privates', '.errored..service_locator.ab2O3uR.App\\Entity\\AdminDocument', NULL, 'Cannot autowire service ".service_locator.ab2O3uR": it needs an instance of "App\\Entity\\AdminDocument" but this type has been excluded in "config/services.yaml".'],
            'adminDocumentRepository' => ['privates', 'App\\Repository\\AdminDocumentRepository', 'getAdminDocumentRepositoryService', true],
        ], [
            'adminDocument' => 'App\\Entity\\AdminDocument',
            'adminDocumentRepository' => 'App\\Repository\\AdminDocumentRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiAdminDocumentController::update()', $container);
    }
}
