<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDistrict2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LrVqBUr.App\Entity\District' shared service.
     *
     * @return \App\Entity\District
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LrVqBUr": it needs an instance of "App\\Entity\\District" but this type has been excluded in "config/services.yaml".');
    }
}
