<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFichierControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MvetcdK.App\Controller\FichierController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MvetcdK.App\\Controller\\FichierController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fichier' => ['privates', '.errored..service_locator.MvetcdK.App\\Entity\\Fichier', NULL, 'Cannot autowire service ".service_locator.MvetcdK": it needs an instance of "App\\Entity\\Fichier" but this type has been excluded in "config/services.yaml".'],
        ], [
            'fichier' => 'App\\Entity\\Fichier',
        ]))->withContext('App\\Controller\\FichierController::show()', $container);
    }
}
