<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNiveauIntervention2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.I4hE2lm.App\Entity\NiveauIntervention' shared service.
     *
     * @return \App\Entity\NiveauIntervention
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.I4hE2lm": it needs an instance of "App\\Entity\\NiveauIntervention" but this type has been excluded in "config/services.yaml".');
    }
}
