<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfessionnelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NG.x1gB.App\Entity\Professionnel' shared service.
     *
     * @return \App\Entity\Professionnel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NG.x1gB": it needs an instance of "App\\Entity\\Professionnel" but this type has been excluded in "config/services.yaml".');
    }
}
