<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaginationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PaginationService' shared autowired service.
     *
     * @return \App\Service\PaginationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PaginationService.php';

        return $container->privates['App\\Service\\PaginationService'] = new \App\Service\PaginationService(($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
