<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3E.PfSh.App\Entity\Region' shared service.
     *
     * @return \App\Entity\Region
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3E.PfSh": it needs an instance of "App\\Entity\\Region" but this type has been excluded in "config/services.yaml".');
    }
}
