<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVilleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7cv2C6b.App\Entity\Ville' shared service.
     *
     * @return \App\Entity\Ville
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7cv2C6b": it needs an instance of "App\\Entity\\Ville" but this type has been excluded in "config/services.yaml".');
    }
}
