<?php

namespace ContainerGbz7pLN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidationWorkflowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oViNYI3.App\Entity\ValidationWorkflow' shared service.
     *
     * @return \App\Entity\ValidationWorkflow
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oViNYI3": it needs an instance of "App\\Entity\\ValidationWorkflow" but this type has been excluded in "config/services.yaml".');
    }
}
