<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UdLrYBIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.udLrYBI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.udLrYBI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adminDocumentRepository' => ['privates', 'App\\Repository\\AdminDocumentRepository', 'getAdminDocumentRepositoryService', true],
        ], [
            'adminDocumentRepository' => 'App\\Repository\\AdminDocumentRepository',
        ]);
    }
}
