<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KsxGMw6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KsxGMw6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KsxGMw6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'libelleGroupeRepository' => ['privates', 'App\\Repository\\LibelleGroupeRepository', 'getLibelleGroupeRepositoryService', true],
            'typeDocumentRepository' => ['privates', 'App\\Repository\\TypeDocumentRepository', 'getTypeDocumentRepositoryService', true],
            'typePersonneRepository' => ['privates', 'App\\Repository\\TypePersonneRepository', 'getTypePersonneRepositoryService', true],
        ], [
            'libelleGroupeRepository' => 'App\\Repository\\LibelleGroupeRepository',
            'typeDocumentRepository' => 'App\\Repository\\TypeDocumentRepository',
            'typePersonneRepository' => 'App\\Repository\\TypePersonneRepository',
        ]);
    }
}
