<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JGT2YJ9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jGT2YJ9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jGT2YJ9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'civiliteRepository' => ['privates', 'App\\Repository\\ValidationWorkflowRepository', 'getValidationWorkflowRepositoryService', true],
        ], [
            'civiliteRepository' => 'App\\Repository\\ValidationWorkflowRepository',
        ]);
    }
}
