<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HMZzy9cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hMZzy9c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hMZzy9c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'tempProfessionnelRepository' => ['privates', 'App\\Repository\\TempProfessionnelRepository', 'getTempProfessionnelRepositoryService', true],
            'paiementService' => ['privates', 'App\\Service\\PaiementService', 'getPaiementServiceService', true],
        ], [
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'tempProfessionnelRepository' => 'App\\Repository\\TempProfessionnelRepository',
            'paiementService' => 'App\\Service\\PaiementService',
        ]);
    }
}
