<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_McTaVe_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.McTaVe.' shared service.
     *
     * @return \Symfony\Component\Workflow\Registry
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Apis\\ApiEtablissementController::active()": the $workflowRegistry argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Workflow\\Registry".');
    }
}
