<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8dODJ0FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8dODJ0F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8dODJ0F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notification' => ['privates', '.errored..service_locator.8dODJ0F.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.8dODJ0F": it needs an instance of "App\\Entity\\Notification" but this type has been excluded in "config/services.yaml".'],
            'notificationRepository' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'notification' => 'App\\Entity\\Notification',
            'notificationRepository' => 'App\\Repository\\NotificationRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
