<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AWP1ntbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aWP1ntb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aWP1ntb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professionnelRepository' => ['privates', 'App\\Repository\\ProfessionnelRepository', 'getProfessionnelRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'professionRepository' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
        ], [
            'professionnelRepository' => 'App\\Repository\\ProfessionnelRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'professionRepository' => 'App\\Repository\\ProfessionRepository',
        ]);
    }
}
