<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BTW6q0YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bTW6q0Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bTW6q0Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'resetPasswordServicee' => ['privates', 'App\\Service\\ResetPasswordService', 'getResetPasswordServiceService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'resetPasswordServicee' => 'App\\Service\\ResetPasswordService',
        ]);
    }
}
