<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLieuDiplomeControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BsA5wRI.App\Controller\Apis\ApiLieuDiplomeController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BsA5wRI.App\\Controller\\Apis\\ApiLieuDiplomeController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\LieuDiplomeRepository', 'getLieuDiplomeRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\LieuDiplomeRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiLieuDiplomeController::deleteAll()', $container);
    }
}
