<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUserControllerresetPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QrATXQA.App\Controller\Apis\ApiUserController::resetPassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QrATXQA.App\\Controller\\Apis\\ApiUserController::resetPassword()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tokenRepo' => ['privates', 'App\\Repository\\ResetPasswordTokenRepository', 'getResetPasswordTokenRepositoryService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'tokenRepo' => 'App\\Repository\\ResetPasswordTokenRepository',
            'passwordHasher' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\Apis\\ApiUserController::resetPassword()', $container);
    }
}
