<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiStatusProControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f.sVVdE.App\Controller\Apis\ApiStatusProController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f.sVVdE.App\\Controller\\Apis\\ApiStatusProController::index()'] = ($container->privates['.service_locator.f.sVVdE'] ?? $container->load('get_ServiceLocator_F_SVVdEService'))->withContext('App\\Controller\\Apis\\ApiStatusProController::index()', $container);
    }
}
