<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiArticleControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SBOQN4t.App\Controller\Apis\ApiArticleController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SBOQN4t.App\\Controller\\Apis\\ApiArticleController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.SBOQN4t.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.SBOQN4t": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'villeRepository' => 'App\\Repository\\ArticleRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiArticleController::delete()', $container);
    }
}
