<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiMessageControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0CgUwQp.App\Controller\Apis\ApiMessageController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0CgUwQp.App\\Controller\\Apis\\ApiMessageController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'message' => ['privates', '.errored..service_locator.0CgUwQp.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.0CgUwQp": it needs an instance of "App\\Entity\\Message" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
        ], [
            'message' => 'App\\Entity\\Message',
            'villeRepository' => 'App\\Repository\\MessageRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiMessageController::delete()', $container);
    }
}
