<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionnelControllerupdateImputationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nuGqx8c.App\Controller\Apis\ApiProfessionnelController::updateImputation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nuGqx8c.App\\Controller\\Apis\\ApiProfessionnelController::updateImputation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professionnel' => ['privates', '.errored..service_locator.nuGqx8c.App\\Entity\\Professionnel', NULL, 'Cannot autowire service ".service_locator.nuGqx8c": it needs an instance of "App\\Entity\\Professionnel" but this type has been excluded in "config/services.yaml".'],
            'professionnelRepository' => ['privates', 'App\\Repository\\ProfessionnelRepository', 'getProfessionnelRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'professionnel' => 'App\\Entity\\Professionnel',
            'professionnelRepository' => 'App\\Repository\\ProfessionnelRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiProfessionnelController::updateImputation()', $container);
    }
}
