<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRacineSequenceControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IKLDxy9.App\Controller\Apis\ApiRacineSequenceController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IKLDxy9.App\\Controller\\Apis\\ApiRacineSequenceController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\RacineSequenceRepository', 'getRacineSequenceRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\RacineSequenceRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiRacineSequenceController::deleteAll()', $container);
    }
}
