<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUserControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uTkqXqk.App\Controller\Apis\ApiUserController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uTkqXqk.App\\Controller\\Apis\\ApiUserController::delete()'] = ($container->privates['.service_locator.uTkqXqk'] ?? $container->load('get_ServiceLocator_UTkqXqkService'))->withContext('App\\Controller\\Apis\\ApiUserController::delete()', $container);
    }
}
