<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeProfessionControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yfDQPjd.App\Controller\Apis\ApiTypeProfessionController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yfDQPjd.App\\Controller\\Apis\\ApiTypeProfessionController::index()'] = ($container->privates['.service_locator.yfDQPjd'] ?? $container->load('get_ServiceLocator_YfDQPjdService'))->withContext('App\\Controller\\Apis\\ApiTypeProfessionController::index()', $container);
    }
}
