<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeProfessionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fGpcnva.App\Controller\Apis\ApiTypeProfessionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fGpcnva.App\\Controller\\Apis\\ApiTypeProfessionController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeProfession' => ['privates', '.errored..service_locator.fGpcnva.App\\Entity\\TypeProfession', NULL, 'Cannot autowire service ".service_locator.fGpcnva": it needs an instance of "App\\Entity\\TypeProfession" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\TypeProfessionRepository', 'getTypeProfessionRepositoryService', true],
        ], [
            'typeProfession' => 'App\\Entity\\TypeProfession',
            'villeRepository' => 'App\\Repository\\TypeProfessionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiTypeProfessionController::delete()', $container);
    }
}
