<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypePersonneControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o8NVy9j.App\Controller\Apis\ApiTypePersonneController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o8NVy9j.App\\Controller\\Apis\\ApiTypePersonneController::create()'] = ($container->privates['.service_locator.o8NVy9j'] ?? $container->load('get_ServiceLocator_O8NVy9jService'))->withContext('App\\Controller\\Apis\\ApiTypePersonneController::create()', $container);
    }
}
