<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDestinateurControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZZdgb0X.App\Controller\Apis\ApiDestinateurController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZZdgb0X.App\\Controller\\Apis\\ApiDestinateurController::index()'] = ($container->privates['.service_locator.ZZdgb0X'] ?? $container->load('get_ServiceLocator_ZZdgb0XService'))->withContext('App\\Controller\\Apis\\ApiDestinateurController::index()', $container);
    }
}
