<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRacineSequenceControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gZiUjs4.App\Controller\Apis\ApiRacineSequenceController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gZiUjs4.App\\Controller\\Apis\\ApiRacineSequenceController::index()'] = ($container->privates['.service_locator.gZiUjs4'] ?? $container->load('get_ServiceLocator_GZiUjs4Service'))->withContext('App\\Controller\\Apis\\ApiRacineSequenceController::index()', $container);
    }
}
