<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaiementControllerwebHookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hMZzy9c.App\Controller\Apis\ApiPaiementController::webHook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.hMZzy9c'] ?? $container->load('get_ServiceLocator_HMZzy9cService'));

        if (isset($container->privates['.service_locator.hMZzy9c.App\\Controller\\Apis\\ApiPaiementController::webHook()'])) {
            return $container->privates['.service_locator.hMZzy9c.App\\Controller\\Apis\\ApiPaiementController::webHook()'];
        }

        return $container->privates['.service_locator.hMZzy9c.App\\Controller\\Apis\\ApiPaiementController::webHook()'] = $a->withContext('App\\Controller\\Apis\\ApiPaiementController::webHook()', $container);
    }
}
