<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCodeGenerateurControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C0mxEn2.App\Controller\Apis\ApiCodeGenerateurController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C0mxEn2.App\\Controller\\Apis\\ApiCodeGenerateurController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utils' => ['privates', 'App\\Service\\Utils', 'getUtilsService', true],
            'racineSequenceRepository' => ['privates', 'App\\Repository\\RacineSequenceRepository', 'getRacineSequenceRepositoryService', true],
            'codeGenerateurRepository' => ['privates', 'App\\Repository\\CodeGenerateurRepository', 'getCodeGenerateurRepositoryService', true],
            'civiliteRepository' => ['privates', 'App\\Repository\\CiviliteRepository', 'getCiviliteRepositoryService', true],
            'professionRepository' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
        ], [
            'utils' => 'App\\Service\\Utils',
            'racineSequenceRepository' => 'App\\Repository\\RacineSequenceRepository',
            'codeGenerateurRepository' => 'App\\Repository\\CodeGenerateurRepository',
            'civiliteRepository' => 'App\\Repository\\CiviliteRepository',
            'professionRepository' => 'App\\Repository\\ProfessionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCodeGenerateurController::create()', $container);
    }
}
