<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAvisControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ejzu_Xg.App\Controller\Apis\ApiAvisController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ejzu_Xg.App\\Controller\\Apis\\ApiAvisController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiAvisController::index()', $container);
    }
}
