<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaiementControllergetTransactionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g53hGhY.App\Controller\Apis\ApiPaiementController::getTransaction()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g53hGhY.App\\Controller\\Apis\\ApiPaiementController::getTransaction()'] = ($container->privates['.service_locator.g53hGhY'] ?? $container->load('get_ServiceLocator_G53hGhYService'))->withContext('App\\Controller\\Apis\\ApiPaiementController::getTransaction()', $container);
    }
}
