<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionnelControllergetExisteCodeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dLsjDil.App\Controller\Apis\ApiProfessionnelController::getExisteCode()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dLsjDil.App\\Controller\\Apis\\ApiProfessionnelController::getExisteCode()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professionnelRepository' => ['privates', 'App\\Repository\\ProfessionnelRepository', 'getProfessionnelRepositoryService', true],
            'codeGenerateurRepository' => ['privates', 'App\\Repository\\CodeGenerateurRepository', 'getCodeGenerateurRepositoryService', true],
        ], [
            'professionnelRepository' => 'App\\Repository\\ProfessionnelRepository',
            'codeGenerateurRepository' => 'App\\Repository\\CodeGenerateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiProfessionnelController::getExisteCode()', $container);
    }
}
