<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAlerteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DybQibG.App\Controller\Apis\ApiAlerteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DybQibG.App\\Controller\\Apis\\ApiAlerteController::index()'] = ($container->privates['.service_locator.DybQibG'] ?? $container->load('get_ServiceLocator_DybQibGService'))->withContext('App\\Controller\\Apis\\ApiAlerteController::index()', $container);
    }
}
