<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeDocumentControllerupdateMultipleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5VTN8nv.App\Controller\Apis\ApiTypeDocumentController::updateMultiple()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5VTN8nv.App\\Controller\\Apis\\ApiTypeDocumentController::updateMultiple()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typePersonne' => ['privates', '.errored..service_locator.5VTN8nv.App\\Entity\\TypePersonne', NULL, 'Cannot autowire service ".service_locator.5VTN8nv": it needs an instance of "App\\Entity\\TypePersonne" but this type has been excluded in "config/services.yaml".'],
            'libelleGroupeRepository' => ['privates', 'App\\Repository\\LibelleGroupeRepository', 'getLibelleGroupeRepositoryService', true],
            'typeDocumentRepository' => ['privates', 'App\\Repository\\TypeDocumentRepository', 'getTypeDocumentRepositoryService', true],
            'typePersonneRepository' => ['privates', 'App\\Repository\\TypePersonneRepository', 'getTypePersonneRepositoryService', true],
        ], [
            'typePersonne' => 'App\\Entity\\TypePersonne',
            'libelleGroupeRepository' => 'App\\Repository\\LibelleGroupeRepository',
            'typeDocumentRepository' => 'App\\Repository\\TypeDocumentRepository',
            'typePersonneRepository' => 'App\\Repository\\TypePersonneRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiTypeDocumentController::updateMultiple()', $container);
    }
}
