<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VHgCey6.App\Controller\Apis\ApiProfessionController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VHgCey6.App\\Controller\\Apis\\ApiProfessionController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profession' => ['privates', '.errored..service_locator.VHgCey6.App\\Entity\\Profession', NULL, 'Cannot autowire service ".service_locator.VHgCey6": it needs an instance of "App\\Entity\\Profession" but this type has been excluded in "config/services.yaml".'],
            'professionRepository' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
            'typeProfessionRepository' => ['privates', 'App\\Repository\\TypeProfessionRepository', 'getTypeProfessionRepositoryService', true],
        ], [
            'profession' => 'App\\Entity\\Profession',
            'professionRepository' => 'App\\Repository\\ProfessionRepository',
            'typeProfessionRepository' => 'App\\Repository\\TypeProfessionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiProfessionController::update()', $container);
    }
}
