<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUserControllerrequestResetPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qgrb8rg.App\Controller\Apis\ApiUserController::requestResetPassword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qgrb8rg.App\\Controller\\Apis\\ApiUserController::requestResetPassword()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'resetPasswordService' => ['privates', 'App\\Service\\ResetPasswordService', 'getResetPasswordServiceService', true],
        ], [
            'userRepo' => 'App\\Repository\\UserRepository',
            'resetPasswordService' => 'App\\Service\\ResetPasswordService',
        ]))->withContext('App\\Controller\\Apis\\ApiUserController::requestResetPassword()', $container);
    }
}
