<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDestinateurControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A168Huy.App\Controller\Apis\ApiDestinateurController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A168Huy.App\\Controller\\Apis\\ApiDestinateurController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'destinateur' => ['privates', '.errored..service_locator.A168Huy.App\\Entity\\Destinateur', NULL, 'Cannot autowire service ".service_locator.A168Huy": it needs an instance of "App\\Entity\\Destinateur" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\DestinateurRepository', 'getDestinateurRepositoryService', true],
        ], [
            'destinateur' => 'App\\Entity\\Destinateur',
            'villeRepository' => 'App\\Repository\\DestinateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiDestinateurController::delete()', $container);
    }
}
