<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiGenreControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CQaKo22.App\Controller\Apis\ApiGenreController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CQaKo22.App\\Controller\\Apis\\ApiGenreController::index()'] = ($container->privates['.service_locator.CQaKo22'] ?? $container->load('get_ServiceLocator_CQaKo22Service'))->withContext('App\\Controller\\Apis\\ApiGenreController::index()', $container);
    }
}
