<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiStatistiqueControllerindexCiviliteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G4Daon7.App\Controller\Apis\ApiStatistiqueController::indexCivilite()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G4Daon7.App\\Controller\\Apis\\ApiStatistiqueController::indexCivilite()'] = ($container->privates['.service_locator.G4Daon7'] ?? $container->load('get_ServiceLocator_G4Daon7Service'))->withContext('App\\Controller\\Apis\\ApiStatistiqueController::indexCivilite()', $container);
    }
}
