<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDistrictControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LrVqBUr.App\Controller\Apis\ApiDistrictController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LrVqBUr.App\\Controller\\Apis\\ApiDistrictController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'district' => ['privates', '.errored..service_locator.LrVqBUr.App\\Entity\\District', NULL, 'Cannot autowire service ".service_locator.LrVqBUr": it needs an instance of "App\\Entity\\District" but this type has been excluded in "config/services.yaml".'],
            'regionRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService', true],
            'districtRepository' => ['privates', 'App\\Repository\\DistrictRepository', 'getDistrictRepositoryService', true],
        ], [
            'district' => 'App\\Entity\\District',
            'regionRepository' => 'App\\Repository\\RegionRepository',
            'districtRepository' => 'App\\Repository\\DistrictRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiDistrictController::update()', $container);
    }
}
