<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAlerteControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yzNzntu.App\Controller\Apis\ApiAlerteController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yzNzntu.App\\Controller\\Apis\\ApiAlerteController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alerteRepository' => ['privates', 'App\\Repository\\AlerteRepository', 'getAlerteRepositoryService', true],
            'destinateurRepository' => ['privates', 'App\\Repository\\DestinateurRepository', 'getDestinateurRepositoryService', true],
        ], [
            'alerteRepository' => 'App\\Repository\\AlerteRepository',
            'destinateurRepository' => 'App\\Repository\\DestinateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiAlerteController::create()', $container);
    }
}
