<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiStatistiqueControllerindexGeneralService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.69wBDFQ.App\Controller\Apis\ApiStatistiqueController::indexGeneral()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.69wBDFQ.App\\Controller\\Apis\\ApiStatistiqueController::indexGeneral()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etablissementRepository' => ['privates', 'App\\Repository\\EtablissementRepository', 'getEtablissementRepositoryService', true],
            'professionRepository' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
            'professionnelRepository' => ['privates', 'App\\Repository\\ProfessionnelRepository', 'getProfessionnelRepositoryService', true],
            'civiliteRepository' => ['privates', 'App\\Repository\\CiviliteRepository', 'getCiviliteRepositoryService', true],
        ], [
            'etablissementRepository' => 'App\\Repository\\EtablissementRepository',
            'professionRepository' => 'App\\Repository\\ProfessionRepository',
            'professionnelRepository' => 'App\\Repository\\ProfessionnelRepository',
            'civiliteRepository' => 'App\\Repository\\CiviliteRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiStatistiqueController::indexGeneral()', $container);
    }
}
