<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeDocumentControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yGQdEDc.App\Controller\Apis\ApiTypeDocumentController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yGQdEDc.App\\Controller\\Apis\\ApiTypeDocumentController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeDocument' => ['privates', '.errored..service_locator.yGQdEDc.App\\Entity\\TypeDocument', NULL, 'Cannot autowire service ".service_locator.yGQdEDc": it needs an instance of "App\\Entity\\TypeDocument" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\TypeDocumentRepository', 'getTypeDocumentRepositoryService', true],
        ], [
            'typeDocument' => 'App\\Entity\\TypeDocument',
            'villeRepository' => 'App\\Repository\\TypeDocumentRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiTypeDocumentController::delete()', $container);
    }
}
