<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLieuDiplomeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wIsGfHW.App\Controller\Apis\ApiLieuDiplomeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wIsGfHW.App\\Controller\\Apis\\ApiLieuDiplomeController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lieuDiplome' => ['privates', '.errored..service_locator.wIsGfHW.App\\Entity\\LieuDiplome', NULL, 'Cannot autowire service ".service_locator.wIsGfHW": it needs an instance of "App\\Entity\\LieuDiplome" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\LieuDiplomeRepository', 'getLieuDiplomeRepositoryService', true],
        ], [
            'lieuDiplome' => 'App\\Entity\\LieuDiplome',
            'villeRepository' => 'App\\Repository\\LieuDiplomeRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiLieuDiplomeController::delete()', $container);
    }
}
