<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiValidationWorkflowControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oViNYI3.App\Controller\Apis\ApiValidationWorkflowController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oViNYI3.App\\Controller\\Apis\\ApiValidationWorkflowController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ValidationWorkflow' => ['privates', '.errored..service_locator.oViNYI3.App\\Entity\\ValidationWorkflow', NULL, 'Cannot autowire service ".service_locator.oViNYI3": it needs an instance of "App\\Entity\\ValidationWorkflow" but this type has been excluded in "config/services.yaml".'],
            'civiliteRepository' => ['privates', 'App\\Repository\\ValidationWorkflowRepository', 'getValidationWorkflowRepositoryService', true],
        ], [
            'ValidationWorkflow' => 'App\\Entity\\ValidationWorkflow',
            'civiliteRepository' => 'App\\Repository\\ValidationWorkflowRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiValidationWorkflowController::update()', $container);
    }
}
