<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eL0UFqG.App\Controller\Apis\ApiProfessionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eL0UFqG.App\\Controller\\Apis\\ApiProfessionController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profession' => ['privates', '.errored..service_locator.eL0UFqG.App\\Entity\\Profession', NULL, 'Cannot autowire service ".service_locator.eL0UFqG": it needs an instance of "App\\Entity\\Profession" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
        ], [
            'profession' => 'App\\Entity\\Profession',
            'villeRepository' => 'App\\Repository\\ProfessionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiProfessionController::delete()', $container);
    }
}
