<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionnelControllerdesactiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pTW4rAJ.App\Controller\Apis\ApiProfessionnelController::desactive()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pTW4rAJ.App\\Controller\\Apis\\ApiProfessionnelController::desactive()'] = ($container->privates['.service_locator.pTW4rAJ'] ?? $container->load('get_ServiceLocator_PTW4rAJService'))->withContext('App\\Controller\\Apis\\ApiProfessionnelController::desactive()', $container);
    }
}
