<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLibelleGroupeControllerindexByLibelleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g2MYXK8.App\Controller\Apis\ApiLibelleGroupeController::indexByLibelle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g2MYXK8.App\\Controller\\Apis\\ApiLibelleGroupeController::indexByLibelle()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'libelleGroupeRepository' => ['privates', 'App\\Repository\\LibelleGroupeRepository', 'getLibelleGroupeRepositoryService', true],
            'typePersonneRepository' => ['privates', 'App\\Repository\\TypePersonneRepository', 'getTypePersonneRepositoryService', true],
        ], [
            'libelleGroupeRepository' => 'App\\Repository\\LibelleGroupeRepository',
            'typePersonneRepository' => 'App\\Repository\\TypePersonneRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiLibelleGroupeController::indexByLibelle()', $container);
    }
}
