<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaysControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..kblsmv.App\Controller\Apis\ApiPaysController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..kblsmv.App\\Controller\\Apis\\ApiPaysController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pays' => ['privates', '.errored..service_locator..kblsmv.App\\Entity\\Pays', NULL, 'Cannot autowire service ".service_locator..kblsmv": it needs an instance of "App\\Entity\\Pays" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\PaysRepository', 'getPaysRepositoryService', true],
        ], [
            'pays' => 'App\\Entity\\Pays',
            'villeRepository' => 'App\\Repository\\PaysRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiPaysController::delete()', $container);
    }
}
