<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCommentaireControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pIYft2d.App\Controller\Apis\ApiCommentaireController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pIYft2d.App\\Controller\\Apis\\ApiCommentaireController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentaire' => ['privates', '.errored..service_locator.pIYft2d.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.pIYft2d": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
            'villeRepository' => 'App\\Repository\\CommentaireRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCommentaireController::delete()', $container);
    }
}
