<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDistrictControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..pYPK7k.App\Controller\Apis\ApiDistrictController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..pYPK7k.App\\Controller\\Apis\\ApiDistrictController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'district' => ['privates', '.errored..service_locator..pYPK7k.App\\Entity\\District', NULL, 'Cannot autowire service ".service_locator..pYPK7k": it needs an instance of "App\\Entity\\District" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\DistrictRepository', 'getDistrictRepositoryService', true],
        ], [
            'district' => 'App\\Entity\\District',
            'villeRepository' => 'App\\Repository\\DistrictRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiDistrictController::delete()', $container);
    }
}
