<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaiementControllerwebHookOepService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LdM_.Xm.App\Controller\Apis\ApiPaiementController::webHookOep()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.LdM_.Xm'] ?? $container->load('get_ServiceLocator_LdM_XmService'));

        if (isset($container->privates['.service_locator.LdM_.Xm.App\\Controller\\Apis\\ApiPaiementController::webHookOep()'])) {
            return $container->privates['.service_locator.LdM_.Xm.App\\Controller\\Apis\\ApiPaiementController::webHookOep()'];
        }

        return $container->privates['.service_locator.LdM_.Xm.App\\Controller\\Apis\\ApiPaiementController::webHookOep()'] = $a->withContext('App\\Controller\\Apis\\ApiPaiementController::webHookOep()', $container);
    }
}
