<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDirectionControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KjYojKb.App\Controller\Apis\ApiDirectionController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KjYojKb.App\\Controller\\Apis\\ApiDirectionController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\DirectionRepository', 'getDirectionRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\DirectionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiDirectionController::deleteAll()', $container);
    }
}
