<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRegionControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hp29FXl.App\Controller\Apis\ApiRegionController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hp29FXl.App\\Controller\\Apis\\ApiRegionController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'regionRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService', true],
            'directionRepository' => ['privates', 'App\\Repository\\DirectionRepository', 'getDirectionRepositoryService', true],
        ], [
            'regionRepository' => 'App\\Repository\\RegionRepository',
            'directionRepository' => 'App\\Repository\\DirectionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiRegionController::create()', $container);
    }
}
