<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiVilleControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3U7jIjB.App\Controller\Apis\ApiVilleController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3U7jIjB.App\\Controller\\Apis\\ApiVilleController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
            'districtRepository' => ['privates', 'App\\Repository\\DistrictRepository', 'getDistrictRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\VilleRepository',
            'districtRepository' => 'App\\Repository\\DistrictRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiVilleController::create()', $container);
    }
}
