<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAvisControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PjeWN1g.App\Controller\Apis\ApiAvisController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PjeWN1g.App\\Controller\\Apis\\ApiAvisController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avis' => ['privates', '.errored..service_locator.PjeWN1g.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.PjeWN1g": it needs an instance of "App\\Entity\\Avis" but this type has been excluded in "config/services.yaml".'],
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
        ], [
            'avis' => 'App\\Entity\\Avis',
            'avisRepository' => 'App\\Repository\\AvisRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiAvisController::update()', $container);
    }
}
