<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProfessionnelControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EzN7xwA.App\Controller\Apis\ApiProfessionnelController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EzN7xwA.App\\Controller\\Apis\\ApiProfessionnelController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sendMailService' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'villeRepository' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
            'civiliteRepository' => ['privates', 'App\\Repository\\CiviliteRepository', 'getCiviliteRepositoryService', true],
            'specialiteRepository' => ['privates', 'App\\Repository\\SpecialiteRepository', 'getSpecialiteRepositoryService', true],
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'professionnelRepository' => ['privates', 'App\\Repository\\ProfessionnelRepository', 'getProfessionnelRepositoryService', true],
            'paysRepository' => ['privates', 'App\\Repository\\PaysRepository', 'getPaysRepositoryService', true],
            'organisationRepository' => ['privates', 'App\\Repository\\OrganisationRepository', 'getOrganisationRepositoryService', true],
            'paiementService' => ['privates', 'App\\Service\\PaiementService', 'getPaiementServiceService', true],
            'situationProfessionnelleRepository' => ['privates', 'App\\Repository\\SituationProfessionnelleRepository', 'getSituationProfessionnelleRepositoryService', true],
            'regionRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService', true],
            'districtRepository' => ['privates', 'App\\Repository\\DistrictRepository', 'getDistrictRepositoryService', true],
            'communeRepository' => ['privates', 'App\\Repository\\CommuneRepository', 'getCommuneRepositoryService', true],
            'typeDiplomeRepository' => ['privates', 'App\\Repository\\TypeDiplomeRepository', 'getTypeDiplomeRepositoryService', true],
            'statusProRepository' => ['privates', 'App\\Repository\\StatusProRepository', 'getStatusProRepositoryService', true],
            'lieuDiplomeRepository' => ['privates', 'App\\Repository\\LieuDiplomeRepository', 'getLieuDiplomeRepositoryService', true],
            'codeGenerateurRepository' => ['privates', 'App\\Repository\\CodeGenerateurRepository', 'getCodeGenerateurRepositoryService', true],
        ], [
            'sendMailService' => 'App\\Service\\SendMailService',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'villeRepository' => 'App\\Repository\\VilleRepository',
            'civiliteRepository' => 'App\\Repository\\CiviliteRepository',
            'specialiteRepository' => 'App\\Repository\\SpecialiteRepository',
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'professionnelRepository' => 'App\\Repository\\ProfessionnelRepository',
            'paysRepository' => 'App\\Repository\\PaysRepository',
            'organisationRepository' => 'App\\Repository\\OrganisationRepository',
            'paiementService' => 'App\\Service\\PaiementService',
            'situationProfessionnelleRepository' => 'App\\Repository\\SituationProfessionnelleRepository',
            'regionRepository' => 'App\\Repository\\RegionRepository',
            'districtRepository' => 'App\\Repository\\DistrictRepository',
            'communeRepository' => 'App\\Repository\\CommuneRepository',
            'typeDiplomeRepository' => 'App\\Repository\\TypeDiplomeRepository',
            'statusProRepository' => 'App\\Repository\\StatusProRepository',
            'lieuDiplomeRepository' => 'App\\Repository\\LieuDiplomeRepository',
            'codeGenerateurRepository' => 'App\\Repository\\CodeGenerateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiProfessionnelController::create()', $container);
    }
}
