<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiNiveauInterventionControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4fIYCGE.App\Controller\Apis\ApiNiveauInterventionController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4fIYCGE.App\\Controller\\Apis\\ApiNiveauInterventionController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'niveauIntervention' => ['privates', '.errored..service_locator.4fIYCGE.App\\Entity\\NiveauIntervention', NULL, 'Cannot autowire service ".service_locator.4fIYCGE": it needs an instance of "App\\Entity\\NiveauIntervention" but this type has been excluded in "config/services.yaml".'],
            'niveauInterventionRepository' => ['privates', 'App\\Repository\\NiveauInterventionRepository', 'getNiveauInterventionRepositoryService', true],
        ], [
            'niveauIntervention' => 'App\\Entity\\NiveauIntervention',
            'niveauInterventionRepository' => 'App\\Repository\\NiveauInterventionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiNiveauInterventionController::update()', $container);
    }
}
