<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDirectionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eB1xdVJ.App\Controller\Apis\ApiDirectionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eB1xdVJ.App\\Controller\\Apis\\ApiDirectionController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'direction' => ['privates', '.errored..service_locator.eB1xdVJ.App\\Entity\\Direction', NULL, 'Cannot autowire service ".service_locator.eB1xdVJ": it needs an instance of "App\\Entity\\Direction" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\DirectionRepository', 'getDirectionRepositoryService', true],
        ], [
            'direction' => 'App\\Entity\\Direction',
            'villeRepository' => 'App\\Repository\\DirectionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiDirectionController::delete()', $container);
    }
}
