<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiNiveauInterventionControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.enlMmRf.App\Controller\Apis\ApiNiveauInterventionController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.enlMmRf.App\\Controller\\Apis\\ApiNiveauInterventionController::create()'] = ($container->privates['.service_locator.enlMmRf'] ?? $container->load('get_ServiceLocator_EnlMmRfService'))->withContext('App\\Controller\\Apis\\ApiNiveauInterventionController::create()', $container);
    }
}
