<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiGenreControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9P.a90S.App\Controller\Apis\ApiGenreController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9P.a90S.App\\Controller\\Apis\\ApiGenreController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'genre' => ['privates', '.errored..service_locator.9P.a90S.App\\Entity\\Genre', NULL, 'Cannot autowire service ".service_locator.9P.a90S": it needs an instance of "App\\Entity\\Genre" but this type has been excluded in "config/services.yaml".'],
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
        ], [
            'genre' => 'App\\Entity\\Genre',
            'genreRepository' => 'App\\Repository\\GenreRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiGenreController::update()', $container);
    }
}
