<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlerteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LS4zByK.App\Entity\Alerte' shared service.
     *
     * @return \App\Entity\Alerte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LS4zByK": it needs an instance of "App\\Entity\\Alerte" but this type has been excluded in "config/services.yaml".');
    }
}
