<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiStatistiqueControllerindexSpecialiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9Kw2Me2.App\Controller\Apis\ApiStatistiqueController::indexSpecialite()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9Kw2Me2.App\\Controller\\Apis\\ApiStatistiqueController::indexSpecialite()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etablissementRepository' => ['privates', 'App\\Repository\\EtablissementRepository', 'getEtablissementRepositoryService', true],
            'professionRepository' => ['privates', 'App\\Repository\\ProfessionRepository', 'getProfessionRepositoryService', true],
            'specialiteRepository' => ['privates', 'App\\Repository\\SpecialiteRepository', 'getSpecialiteRepositoryService', true],
        ], [
            'etablissementRepository' => 'App\\Repository\\EtablissementRepository',
            'professionRepository' => 'App\\Repository\\ProfessionRepository',
            'specialiteRepository' => 'App\\Repository\\SpecialiteRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiStatistiqueController::indexSpecialite()', $container);
    }
}
