<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiStatistiqueControllerindexByTypeUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q0Ag4cn.App\Controller\Apis\ApiStatistiqueController::indexByTypeUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q0Ag4cn.App\\Controller\\Apis\\ApiStatistiqueController::indexByTypeUser()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etablissementRepository' => ['privates', 'App\\Repository\\EtablissementRepository', 'getEtablissementRepositoryService', true],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'professionnelRepository' => ['privates', 'App\\Repository\\ProfessionnelRepository', 'getProfessionnelRepositoryService', true],
        ], [
            'etablissementRepository' => 'App\\Repository\\EtablissementRepository',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'professionnelRepository' => 'App\\Repository\\ProfessionnelRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiStatistiqueController::indexByTypeUser()', $container);
    }
}
