<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRegionControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3E.PfSh.App\Controller\Apis\ApiRegionController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3E.PfSh.App\\Controller\\Apis\\ApiRegionController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'region' => ['privates', '.errored..service_locator.3E.PfSh.App\\Entity\\Region', NULL, 'Cannot autowire service ".service_locator.3E.PfSh": it needs an instance of "App\\Entity\\Region" but this type has been excluded in "config/services.yaml".'],
            'regionRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService', true],
            'directionRepository' => ['privates', 'App\\Repository\\DirectionRepository', 'getDirectionRepositoryService', true],
        ], [
            'region' => 'App\\Entity\\Region',
            'regionRepository' => 'App\\Repository\\RegionRepository',
            'directionRepository' => 'App\\Repository\\DirectionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiRegionController::update()', $container);
    }
}
