<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiSituationProfessionnelleControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5uI5324.App\Controller\Apis\ApiSituationProfessionnelleController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5uI5324.App\\Controller\\Apis\\ApiSituationProfessionnelleController::create()'] = ($container->privates['.service_locator.5uI5324'] ?? $container->load('get_ServiceLocator_5uI5324Service'))->withContext('App\\Controller\\Apis\\ApiSituationProfessionnelleController::create()', $container);
    }
}
