<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCommentaireControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bc48Cst.App\Controller\Apis\ApiCommentaireController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bc48Cst.App\\Controller\\Apis\\ApiCommentaireController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentaire' => ['privates', '.errored..service_locator.bc48Cst.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.bc48Cst": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".'],
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'commentaireRepository' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'commentaireRepository' => 'App\\Repository\\CommentaireRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCommentaireController::update()', $container);
    }
}
