<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiValidationWorkflowControllersuiviByUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WPmbfTg.App\Controller\Apis\ApiValidationWorkflowController::suiviByUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WPmbfTg.App\\Controller\\Apis\\ApiValidationWorkflowController::suiviByUser()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'validationWorkflowRepository' => ['privates', 'App\\Repository\\ValidationWorkflowRepository', 'getValidationWorkflowRepositoryService', true],
        ], [
            'validationWorkflowRepository' => 'App\\Repository\\ValidationWorkflowRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiValidationWorkflowController::suiviByUser()', $container);
    }
}
