<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiLibelleGroupeControllerindexByLibelleOepService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uN0ME0r.App\Controller\Apis\ApiLibelleGroupeController::indexByLibelleOep()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uN0ME0r.App\\Controller\\Apis\\ApiLibelleGroupeController::indexByLibelleOep()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'libelleGroupeRepository' => ['privates', 'App\\Repository\\LibelleGroupeRepository', 'getLibelleGroupeRepositoryService', true],
            'typePersonne' => ['privates', '.errored..service_locator.uN0ME0r.App\\Entity\\TypePersonne', NULL, 'Cannot autowire service ".service_locator.uN0ME0r": it needs an instance of "App\\Entity\\TypePersonne" but this type has been excluded in "config/services.yaml".'],
        ], [
            'libelleGroupeRepository' => 'App\\Repository\\LibelleGroupeRepository',
            'typePersonne' => 'App\\Entity\\TypePersonne',
        ]))->withContext('App\\Controller\\Apis\\ApiLibelleGroupeController::indexByLibelleOep()', $container);
    }
}
