<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDestinateurControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zu_bA_k.App\Controller\Apis\ApiDestinateurController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zu_bA_k.App\\Controller\\Apis\\ApiDestinateurController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'destinateur' => ['privates', '.errored..service_locator.zu_bA_k.App\\Entity\\Destinateur', NULL, 'Cannot autowire service ".service_locator.zu_bA_k": it needs an instance of "App\\Entity\\Destinateur" but this type has been excluded in "config/services.yaml".'],
            'destinateurRepository' => ['privates', 'App\\Repository\\DestinateurRepository', 'getDestinateurRepositoryService', true],
        ], [
            'destinateur' => 'App\\Entity\\Destinateur',
            'destinateurRepository' => 'App\\Repository\\DestinateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiDestinateurController::update()', $container);
    }
}
