<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDistrictControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..alBVNI.App\Controller\Apis\ApiDistrictController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..alBVNI.App\\Controller\\Apis\\ApiDistrictController::index()'] = ($container->privates['.service_locator..alBVNI'] ?? $container->load('get_ServiceLocator__AlBVNIService'))->withContext('App\\Controller\\Apis\\ApiDistrictController::index()', $container);
    }
}
