<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiNiveauInterventionControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w4v6QC_.App\Controller\Apis\ApiNiveauInterventionController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w4v6QC_.App\\Controller\\Apis\\ApiNiveauInterventionController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\NiveauInterventionRepository', 'getNiveauInterventionRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\NiveauInterventionRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiNiveauInterventionController::deleteAll()', $container);
    }
}
