<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiDirectionControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C17eaUU.App\Controller\Apis\ApiDirectionController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C17eaUU.App\\Controller\\Apis\\ApiDirectionController::create()'] = ($container->privates['.service_locator.C17eaUU'] ?? $container->load('get_ServiceLocator_C17eaUUService'))->withContext('App\\Controller\\Apis\\ApiDirectionController::create()', $container);
    }
}
