<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAlerteControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LgSxUgD.App\Controller\Apis\ApiAlerteController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LgSxUgD.App\\Controller\\Apis\\ApiAlerteController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alerte' => ['privates', '.errored..service_locator.LgSxUgD.App\\Entity\\Alerte', NULL, 'Cannot autowire service ".service_locator.LgSxUgD": it needs an instance of "App\\Entity\\Alerte" but this type has been excluded in "config/services.yaml".'],
            'alerteRepository' => ['privates', 'App\\Repository\\AlerteRepository', 'getAlerteRepositoryService', true],
            'destinateurRepository' => ['privates', 'App\\Repository\\DestinateurRepository', 'getDestinateurRepositoryService', true],
        ], [
            'alerte' => 'App\\Entity\\Alerte',
            'alerteRepository' => 'App\\Repository\\AlerteRepository',
            'destinateurRepository' => 'App\\Repository\\DestinateurRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiAlerteController::update()', $container);
    }
}
