<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiResetPasswordControllerresetEmailAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bTW6q0Y.App\Controller\Apis\ApiResetPasswordController::resetEmailAdmin()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bTW6q0Y.App\\Controller\\Apis\\ApiResetPasswordController::resetEmailAdmin()'] = ($container->privates['.service_locator.bTW6q0Y'] ?? $container->load('get_ServiceLocator_BTW6q0YService'))->withContext('App\\Controller\\Apis\\ApiResetPasswordController::resetEmailAdmin()', $container);
    }
}
