<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypePersonneControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pcvewRv.App\Controller\Apis\ApiTypePersonneController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pcvewRv.App\\Controller\\Apis\\ApiTypePersonneController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typePersonne' => ['privates', '.errored..service_locator.pcvewRv.App\\Entity\\TypePersonne', NULL, 'Cannot autowire service ".service_locator.pcvewRv": it needs an instance of "App\\Entity\\TypePersonne" but this type has been excluded in "config/services.yaml".'],
            'typePersonneRepository' => ['privates', 'App\\Repository\\TypePersonneRepository', 'getTypePersonneRepositoryService', true],
        ], [
            'typePersonne' => 'App\\Entity\\TypePersonne',
            'typePersonneRepository' => 'App\\Repository\\TypePersonneRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiTypePersonneController::update()', $container);
    }
}
