<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCiviliteControllerdeleteAllService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.act9A_6.App\Controller\Apis\ApiCiviliteController::deleteAll()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.act9A_6.App\\Controller\\Apis\\ApiCiviliteController::deleteAll()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'villeRepository' => ['privates', 'App\\Repository\\CiviliteRepository', 'getCiviliteRepositoryService', true],
        ], [
            'villeRepository' => 'App\\Repository\\CiviliteRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCiviliteController::deleteAll()', $container);
    }
}
