<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPaiementControllerdoPaiementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LdM_.Xm.App\Controller\Apis\ApiPaiementController::doPaiement()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LdM_.Xm.App\\Controller\\Apis\\ApiPaiementController::doPaiement()'] = ($container->privates['.service_locator.LdM_.Xm'] ?? $container->load('get_ServiceLocator_LdM_XmService'))->withContext('App\\Controller\\Apis\\ApiPaiementController::doPaiement()', $container);
    }
}
