<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiAdminDocumentControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DI1TlmK.App\Controller\Apis\ApiAdminDocumentController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DI1TlmK.App\\Controller\\Apis\\ApiAdminDocumentController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'adminDocument' => ['privates', '.errored..service_locator.DI1TlmK.App\\Entity\\AdminDocument', NULL, 'Cannot autowire service ".service_locator.DI1TlmK": it needs an instance of "App\\Entity\\AdminDocument" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\AdminDocumentRepository', 'getAdminDocumentRepositoryService', true],
        ], [
            'adminDocument' => 'App\\Entity\\AdminDocument',
            'villeRepository' => 'App\\Repository\\AdminDocumentRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiAdminDocumentController::delete()', $container);
    }
}
