<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTypeDocumentControllerindexByLibelleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.icgBrei.App\Controller\Apis\ApiTypeDocumentController::indexByLibelle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.icgBrei.App\\Controller\\Apis\\ApiTypeDocumentController::indexByLibelle()'] = ($container->privates['.service_locator.icgBrei'] ?? $container->load('get_ServiceLocator_IcgBreiService'))->withContext('App\\Controller\\Apis\\ApiTypeDocumentController::indexByLibelle()', $container);
    }
}
