<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiCommuneControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8B2DYwk.App\Controller\Apis\ApiCommuneController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8B2DYwk.App\\Controller\\Apis\\ApiCommuneController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commune' => ['privates', '.errored..service_locator.8B2DYwk.App\\Entity\\Commune', NULL, 'Cannot autowire service ".service_locator.8B2DYwk": it needs an instance of "App\\Entity\\Commune" but this type has been excluded in "config/services.yaml".'],
            'villeRepository' => ['privates', 'App\\Repository\\CommuneRepository', 'getCommuneRepositoryService', true],
        ], [
            'commune' => 'App\\Entity\\Commune',
            'villeRepository' => 'App\\Repository\\CommuneRepository',
        ]))->withContext('App\\Controller\\Apis\\ApiCommuneController::delete()', $container);
    }
}
