<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiForumControllergetOneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3JVGcnR.App\Controller\Apis\ApiForumController::getOne()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3JVGcnR.App\\Controller\\Apis\\ApiForumController::getOne()'] = ($container->privates['.service_locator.3JVGcnR'] ?? $container->load('get_ServiceLocator_3JVGcnRService'))->withContext('App\\Controller\\Apis\\ApiForumController::getOne()', $container);
    }
}
