<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiEtablissementControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KAWz6Zf.App\Controller\Apis\ApiEtablissementController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KAWz6Zf.App\\Controller\\Apis\\ApiEtablissementController::index()'] = ($container->privates['.service_locator.KAWz6Zf'] ?? $container->load('get_ServiceLocator_KAWz6ZfService'))->withContext('App\\Controller\\Apis\\ApiEtablissementController::index()', $container);
    }
}
