<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.byvly3F.App\Controller\AuthController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.byvly3F.App\\Controller\\AuthController::login()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jwtService' => ['privates', 'App\\Service\\JwtService', 'getJwtServiceService', true],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'jwtService' => 'App\\Service\\JwtService',
            'hasher' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\AuthController::login()', $container);
    }
}
