<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodeGenerateurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QQB.3t3.App\Entity\CodeGenerateur' shared service.
     *
     * @return \App\Entity\CodeGenerateur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QQB.3t3": it needs an instance of "App\\Entity\\CodeGenerateur" but this type has been excluded in "config/services.yaml".');
    }
}
