<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDestinateurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A168Huy.App\Entity\Destinateur' shared service.
     *
     * @return \App\Entity\Destinateur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A168Huy": it needs an instance of "App\\Entity\\Destinateur" but this type has been excluded in "config/services.yaml".');
    }
}
