<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDirectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K2nuJiy.App\Entity\Direction' shared service.
     *
     * @return \App\Entity\Direction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.K2nuJiy": it needs an instance of "App\\Entity\\Direction" but this type has been excluded in "config/services.yaml".');
    }
}
