<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLibelleGroupe2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ETUrCGm.App\Entity\LibelleGroupe' shared service.
     *
     * @return \App\Entity\LibelleGroupe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ETUrCGm": it needs an instance of "App\\Entity\\LibelleGroupe" but this type has been excluded in "config/services.yaml".');
    }
}
