<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeDocumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yGQdEDc.App\Entity\TypeDocument' shared service.
     *
     * @return \App\Entity\TypeDocument
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yGQdEDc": it needs an instance of "App\\Entity\\TypeDocument" but this type has been excluded in "config/services.yaml".');
    }
}
