<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypePersonne3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qdUEtu2.App\Entity\TypePersonne' shared service.
     *
     * @return \App\Entity\TypePersonne
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qdUEtu2": it needs an instance of "App\\Entity\\TypePersonne" but this type has been excluded in "config/services.yaml".');
    }
}
