<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Utils' shared autowired service.
     *
     * @return \App\Service\Utils
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/FileTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Utils.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileUploader.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Utils'])) {
            return $container->privates['App\\Service\\Utils'];
        }

        return $container->privates['App\\Service\\Utils'] = new \App\Service\Utils(new \App\Service\FileUploader(), $a);
    }
}
