<?php

namespace ContainerQNxtrvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllertoggleActiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YlAh0cN.App\Controller\UserController::toggleActive()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YlAh0cN.App\\Controller\\UserController::toggleActive()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.YlAh0cN.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.YlAh0cN": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'repository' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\UserController::toggleActive()', $container);
    }
}
