<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGbz7pLN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGbz7pLN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGbz7pLN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGbz7pLN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGbz7pLN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gbz7pLN',
    'container.build_id' => '92401b66',
    'container.build_time' => 1760569193,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGbz7pLN');
