<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPaQrv2l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPaQrv2l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPaQrv2l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPaQrv2l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPaQrv2l\App_KernelDevDebugContainer([
    'container.build_hash' => 'PaQrv2l',
    'container.build_id' => '92bcf255',
    'container.build_time' => 1761323091,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPaQrv2l');
